### ISSUE TITLE
Credentials accidentally included

### ISSUE THREAD

**Issue by Plazmaz** [beststrelok/bonbons#2]
Hello! I'd like to bring to your attention that your email and database credentials are exposed publicly through https://github.com/beststrelok/bonbons/raw/36478000f5f458a012c0ef10643c912b4954b9b4/server.env
Please note that this data cannot be removed from GitHub. A commit removing this information would not delete the link above. The only solution to protect your data is to change your passwords where relevant. I *strongly* suggest you look at https://help.github.com/articles/remove-sensitive-data/ and change your password.
You can read more about avoiding incidents like this in the future [here](https://blog.gitprime.com/using-gitignore-a-practical-guide).

**Comment by beststrelok** [comment]
Thanks!
